cc_library(
    name = "html",
    visibility = ["//visibility:public"],
    deps = [
        ":attribute",
        ":tags",
        ":text",
    ],
)

cc_library(
    name = "attribute",
    hdrs = ["attribute.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "tags",
    hdrs = ["tags.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "text",
    hdrs = ["text.h"],
    visibility = ["//visibility:public"],
)
