cc_library(
    name = "pulse",
    visibility = ["//visibility:public"],
    deps = [
        "//pulse/concurrent",
        "//pulse/dsa",
        "//pulse/html",
        "//pulse/http",
        "//pulse/json",
        "//pulse/net",
    ],
)
